### ISSUE TITLE
As a researcher funded by the FWF, who is corresponding author of a paper in “ACS Applied Nano Materials” (ACS) and currently affiliated with Leiden University (NL), I want to know what my options are to fulfil Plan S.

### ISSUE THREAD

**Issue by KRieck** [antleaf/jct-user-stories#19] opened 2020-06-15 12:25 UTC

**Comment by richard-jones** [comment] 2020-09-25 11:11
Duplicate of #18

**Closed as completed by richard-jones** 2020-09-25 11:11 UTC
Labels: duplicate
